# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         'Проекты Сергея Тимакина'
url:                 https://mikrobic.github.io
baseurl:             "/lanyon"
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Sergey Timakin
  url:               
  email:             timakin1983@mail.ru

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
