# Setup
title: "Не Автор"
tagline: "Тимакин Сергей"
description: "Проекты Сергея Тимакина"
url: "https://mikrobic.github.io"
baseurl: "/lanyon"
paginate: 5
permalink: /lanyon/for_me/

# About/contact
author:
  name: "Sergey Timakin"
  url: "https://vk.com/id228360884"
  email: "timakin1983@mail.ru"

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom vars
version: "1.1.0"
google_analytics_id: #UA-XXXX-Y


# Build settings
markdown: kramdown
highlighter: rouge
sass:
  style: compressed

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - LICENSE.md
