# Setup
title: "Автор"
tagline: "Тимакин Сергей"
description: "Проекты Сергея Тимакина"
url: "https://mikrobic.github.io"
baseurl: "/lanyon"
paginate: 5
permalink: /:baseurl/:path/

# About/contact
author:
  name: "Sergey Timakin"
  url: ""
  email: "timakin1983@mail.ru"

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom vars
version: "1.1.0"
google_analytics_id: #UA-XXXX-Y

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      sidebar: true
  
  - scope:
      path: "pages/project"
      type: "pages"
    values:
      layout: "page"
      parent: "project"
      permalink: /:baseurl/project/:title/

navigation:
  main:
    - title: "Главная"
      url: "/"
      order: 1
    - title: Обо мне
      url: "/for_me/"
      order: 2 
    - title: "Проекты"
      url: "/projects/"
      order: 3

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  style: compressed

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - LICENSE.md
